### ISSUE TITLE
Epic: allow config file to be edited with a local web interface

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/faceloader#12]
Prob need to do a little sketch for this one?

- [ ] I can set my username and password 
- [ ] I can set the list of Facebook pages i want to download
- [ ] I can see if there are any errors imported
- [ ] I can see the events from each calendar in an easy-to-read format

**Comment by kimadactyl** [comment]
Maybe there is an existing third party ical file viewer we can use - there is on Ubuntu apparently
